server:
  port: 12001

spring:
  application:
    name: drug-server
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://101.200.58.159:3306/medical?useUnicode=true&charcterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/medical?useUnicode=true&charcterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        #        server-addr: 101.200.58.159:8848
        server-addr: localhost:8848

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl