server:
  port: 8001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: public
          uri: lb://public-server
          predicates:
            - Path=/pub/**
          filters:
            - StripPrefix=1
        - id: doctor
          uri: lb://doctor-server
          predicates:
            - Path=/doctor/**
          filters:
            - StripPrefix=1
        - id: outpatient
          uri: lb://outpatient-server
          predicates:
            - Path=/outpatient/**
          filters:
            - StripPrefix=1
        - id: drug
          uri: lb://drug-server
          predicates:
            - Path=/drug/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
         server-addr: 101.200.58.159:8848
