server:
  port: 8001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: public
          # uri: http://localhost:9001
          uri: lb://public-server
          predicates:
            - Path=/pub/**
          filters:
            - StripPrefix=1
        - id: doctor
          # uri: http://localhost:10001
          uri: lb://doctor-server
          predicates:
            - Path=/doctor/**
          filters:
            - StripPrefix=1
        - id: outpatient
          # uri: http://localhost:10001
          uri: lb://outpatient-server
          predicates:
            - Path=/outpatient/**
          filters:
            - StripPrefix=1
        - id: drug
          # uri: http://localhost:10001
          uri: lb://drug-server
          predicates:
            - Path=/drug/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        # server-addr: 101.200.58.159:8848
        server-addr: localhost:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
